services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-atendeja}
      POSTGRES_USER: ${POSTGRES_USER:-atendeja}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-atendeja}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-atendeja}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST_PORT:-6380}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_HOST_PORT:-8001}:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["celery", "-A", "app.workers.celery_app.celery", "worker", "--loglevel=INFO"]

  adminer:
    image: adminer:4
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${ADMINER_HOST_PORT:-8081}:8080"

  # Optional profile: Metabase for business dashboards
  metabase:
    image: metabase/metabase:latest
    profiles: ["dashboards"]
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data
    ports:
      - "${METABASE_HOST_PORT:-3001}:3000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
    depends_on:
      api:
        condition: service_started
    ports:
      - "${WEB_HOST_PORT:-8083}:80"
    volumes:
      - ./frontend/ui/public/env.js:/usr/share/nginx/html/env.js:ro
      - ./frontend/ui/public/config.json:/usr/share/nginx/html/config.json:ro

volumes:
  pgdata:
  metabase-data:
